# This is a simple ansible playbook for installing packages needed by blivet-gui
# test suites.
# You can do this by using 'make install-requires' or manually using
# 'ansible-playbook -K -i "localhost," -c local install-test-dependencies.yml'
# Currently only Fedora and Debian are supported by this playbook.

---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Include tasks from blivet-gui-tasks.yml
    ansible.builtin.include_tasks: blivet-gui-tasks.yml
