#
# A Vagrantfile template that can be used for creating machines for blivet-gui
# development/testing.
#
# Use 'vagrant up && vagrant ssh' to spawn the default machine (most recent
# Fedora) and ssh into it or e.g. 'vagrant up blivet-gui-f38 && vagrant ssh blivet-gui-f38'
# to use a Fedora 38 based machine, etc.
#

def os_cpu_cores
  case RbConfig::CONFIG['host_os']
  when /darwin/
    Integer(`sysctl -n hw.ncpu`)
  when /linux/
    Integer(`getconf _NPROCESSORS_ONLN`)
  else
    raise StandardError, "Unsupported platform"
  end
end

Vagrant.configure("2") do |config|
  # common configuration

  config.vm.synced_folder "../", "/home/vagrant/blivet-gui/",
                          type: "rsync", rsync__args: ["-a", "-l", "--exclude=misc"]  # override the default args

  # CHECK THAT THE BELOW OPTIONS ARE OKAY FOR YOUR HW
  config.vm.provider :libvirt do |v|
    v.memory = "2048"
    v.cpus = os_cpu_cores
    v.disk_driver :cache => "unsafe"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "install-test-dependencies.yml"
  end

  config.vm.define "blivet-gui-f38", primary: true, autostart: true do |f38|
    f38.vm.box = "fedora/38-cloud-base"
  end

  config.vm.define "blivet-gui-f37", primary: false, autostart: false do |f37|
    f37.vm.box = "fedora/37-cloud-base"
  end

  config.vm.define "blivet-gui-ubuntu-2204", primary: false, autostart: false do |jammy|
    jammy.vm.box = "generic/ubuntu2204"
  end

  config.vm.define "blivet-gui-debian-testing", primary: false, autostart: false do |testing|
    testing.vm.box = "debian/testing64"
  end

  config.vm.define "blivet-gui-opensuse", primary: false, autostart: false do |suse|
    suse.vm.box = "opensuse/Tumbleweed.x86_64"
  end
end
