actions:
  get-current-version:
    - "python3 ./setup.py --version"
  create-archive:
    - "make local"
    - 'bash -c "ls *.tar*"'

jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all
    - centos-stream-10-x86_64
  trigger: pull_request

- job: tests
  trigger: pull_request
  targets:
  - fedora-latest-stable

- job: copr_build
  trigger: commit
  owner: "@storage"
  project: blivet-daily
  branch: main
  preserve_project: true
  actions:
    get-current-version:
      - "python3 ./setup.py --version"
    create-archive:
      - "make local"
      - 'bash -c "ls *.tar*"'
    post-upstream-clone:
      # bump release to 99 to always be ahead of Fedora builds
      - 'bash -c "sed -i -r \"s/Release:(\s*)\S+/Release: 99%{?dist}/\" blivet-gui.spec"'

- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-all

- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-all

- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-branched

srpm_build_deps:
 - make
 - gettext
 - python3-devel
 - python3-setuptools
 - desktop-file-utils
 - libappstream-glib

downstream_package_name: blivet-gui
