#!/usr/bin/python2
# -*- coding: utf-8 -*-
# Main
#
# Copyright (C) 2014  Red Hat, Inc.
#
# This copyrighted material is made available to anyone wishing to use,
# modify, copy, or redistribute it subject to the terms and conditions of
# the GNU General Public License v.2, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY expressed or implied, including the implied warranties of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.  You should have received a copy of the
# GNU General Public License along with this program; if not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.  Any Red Hat trademarks that are incorporated in the
# source code or documentation are not subject to the GNU General Public
# License and may only be used or replicated with the express permission of
# Red Hat, Inc.
#
# Red Hat Author(s): Vojtech Trefny <vtrefny@redhat.com>
#
#------------------------------------------------------------------------------#

from __future__ import print_function

import os
import stat
import atexit

from six.moves import socketserver

from blivetgui.blivetguiproxy.server import BlivetUtilsServer

SOCK_FILE = "/tmp/blivet-gui.sock" #FIXME

class BlivetGUIServer(socketserver.UnixStreamServer):

    quit = False

    def serve_forever(self):
        while not self.quit:
            self.handle_request()

def remove_sock_file(filename):
    try:
        os.remove(filename)

    except OSError:
        pass

if __name__ == "__main__":
    server = BlivetGUIServer(SOCK_FILE , BlivetUtilsServer)
    os.chmod(SOCK_FILE, stat.S_IWOTH) #FIXME
    atexit.register(remove_sock_file, filename=SOCK_FILE)
    print("Server ready!")

    # Activate the server; this will keep running until you
    # interrupt the program with Ctrl-C
    server.serve_forever()
