#!/usr/bin/python2 

import optparse

import blivetgui.main

def parse_options():
	"""
	Parses command-line arguments passed to blivet_gui
	"""
	parser = optparse.OptionParser()
	parser.add_option("-v", "--version", action="store_true", dest="version", 
				   default=False,help="show version information")
	parser.add_option("-e", "--embeded", action="store_true", dest="embeded", 
				   default=False,help="embed this application")

	(options, args) = parser.parse_args()
	
	return options

blivetgui.main.main(parse_options())