# This is a simple ansible playbook for installing packages needed by blivet-gui
# test suites.
# You can do this by using 'make install-requires' or manually using
# 'ansible-playbook -K -i "localhost," -c local install-test-dependencies.yml'
# Currently only Fedora and Debian are supported by this playbook.

---
- hosts: all
  become: true

  tasks:
  - name: Install test dependencies (Fedora)
    package: name={{item}} state=installed
    with_items:
      - python3-mock
      - python3-coverage
      - python3-pocketlint
      - python3-pep8
      - xorg-x11-server-Xvfb
      - targetcli
      - gettext
      - python3-polib
    when: ansible_distribution == "Fedora"

  - name: Install test dependencies (Debian)
    package: name={{item}} state=installed
    with_items:
      - python3-mock
      - python3-coverage
      - python3-pep8
      - pep8
      - xvfb
      - targetcli-fb
      - python3-pip
      - gettext
      - python3-polib
    when: ansible_distribution == "Debian"

  # pocketlint is not packaged on Debian
  - name: Install pocketlint using pip (Debian)
    pip: name=git+http://github.com/rhinstaller/pocketlint executable=pip3
    when: ansible_distribution == "Debian"

  # packaged versions of pylint and astroid are too old on Debian
  - name: Install newest pylint and astroid using pip (Debian)
    pip: name={{item}} executable=pip3
    with_items:
      - astroid
      - pylint
    when: ansible_distribution == "Debian"
